### ISSUE TITLE
Issue Label 수정 및 공지사항

### ISSUE THREAD

**Issue by Seobeomsu** [Seobeomsu/2023_Open_Source_Project#1]
issue label들을 적당히 만들어봤습니다.
이후 작성하실때 label을 붙여서 작성해주시면 되겠습니다.
issue 작성하실떄 assigneers 체크해주셔야지 알람이가므로 가능하면 해주시길바랍니다.
또는 카톡방에 issue 업데이트되었다고 알려주시면 되겠습니다.
issue 올리는거에 부담가지지 마시고 궁금한거나 물어볼거 정할거있으면 편하게 작성해주세요!
감사합니다.

**Comment by AhnJewon** [comment]
확인했습니다.
