### ISSUE TITLE
api 실행 관련 질문

### ISSUE THREAD

**Issue by yangsua** [Seobeomsu/2023_Open_Source_Project#10]
중기예보 api를 실행해보려 했으나
http://[apis.data.go.kr/1360000/MidFcstInfoService/getMidLandFcst?serviceKey=Cy2hhB4CjnW9YfGUIRuM8eJD2ywoJH1SBWFqYHxWi45mcv79MUbHVrYA1XK%2BeAKvgo45fGbS2%2B68GnXROF6ipw%3D%3D&numOfRows=10&pageNo=1&regId=11B00000&tmFc=201310171800](http://apis.data.go.kr/1360000/MidFcstInfoService/getMidLandFcst?serviceKey=Cy2hhB4CjnW9YfGUIRuM8eJD2ywoJH1SBWFqYHxWi45mcv79MUbHVrYA1XK%2BeAKvgo45fGbS2%2B68GnXROF6ipw%3D%3D&numOfRows=10&pageNo=1&regId=11B00000&tmFc=201310171800)

이러한 메시지가 뜨게 되는데, 이 다음에 어떻게 진행해야하는지 감이 잡히질 않습니다. 도와주시면 감사하겠습니다.

**Comment by Seobeomsu** [comment]
![image](https://github.com/Seobeomsu/2023_Open_Source_Project/assets/48756063/ddaba4a0-b8b2-4d8e-97cf-beb6df66b6cd)
에러코드 99는 기타에러라서 어떤게 문제인지 알기어렵습니다.
힘내십쇼 ㅠㅠ

**Comment by AhnJewon** [comment]
제가 확인해 보니 오늘 날짜 기준 24시간 전 자료까지만 조회할 수 있는 것 같아요
<img width="364" alt="image" src="https://github.com/Seobeomsu/2023_Open_Source_Project/assets/127263680/d323cda8-3c5c-4bcb-93a5-93656f0f67d5">

지금이 시간이 202305251300이면 거기서 24시간 전인 202305250600, 202305241800 까지만 조회가능 한 것 같아요
