### ISSUE TITLE
사용할 api 알림

### ISSUE THREAD

**Issue by yangsua** [Seobeomsu/2023_Open_Source_Project#12]
http://[apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst?serviceKey=Cy2hhB4CjnW9YfGUIRuM8eJD2ywoJH1SBWFqYHxWi45mcv79MUbHVrYA1XK%2BeAKvgo45fGbS2%2B68GnXROF6ipw%3D%3D&numOfRows=10&pageNo=1&base_date=20210628&base_time=0500&nx=55&ny=127](http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst?serviceKey=Cy2hhB4CjnW9YfGUIRuM8eJD2ywoJH1SBWFqYHxWi45mcv79MUbHVrYA1XK%2BeAKvgo45fGbS2%2B68GnXROF6ipw%3D%3D&numOfRows=10&pageNo=1&base_date=20210628&base_time=0500&nx=55&ny=127)

단기예보로 글피까지의 날씨예보를 알 수 있는 api를 사용하도록하겠습니다.

**Comment by Seobeomsu** [comment]
감사합니다
