### ISSUE TITLE
front <-> backend 전송할 데이터

### ISSUE THREAD

**Issue by Seobeomsu** [Seobeomsu/2023_Open_Source_Project#13]
front 에서 보낼내용
지역 코드 , 활동  // 예시 {
{ legioncode: 1, activity: "꽃놀이" }

기상청 api에서 어떤 지역코드가 어느지역인지 적어주시면 감사하겠습니다.

backend에서 보낼내용
id , date , weather , hightempature , low tempature , state ( 좋은날인지 아닌지 구분)
 { id : 1 ,date : "5.31", weather : "good", hightempature : "45", lowtempature : "-45" , state : "bad"},
데이터 주는거 추가하실게있으면 알려주세요

activity는 
꽃놀이 , 물놀이 , 캠핑 , 피크닉 , 별관측 으로 5가지만 하겠습니다. 추가하실꺼면 말씀하세요.

**Comment by Seobeomsu** [comment]
아참 추가로 웹사이트 크롤링해서 관광지데이터를 보여주기로했는데
다음과 같은 형식으로 주시면 감사하겠습니다.
  { id : 1,name : "충북대", address : "청주시 서원구 서원로 1길" , context : "종강시켜줘!!" , imageaddress : "/asdfsaf"},

**Comment by Seobeomsu** [comment]
크롤링 데이터에서 id는 안보내주셔도됩니다.

**Comment by yangsua** [comment]
별관측하기 좋은 날만하기로 한거 아니었나요?

**Comment by Seobeomsu** [comment]
죄송합니다 제가 기억이 잘안나서 ...
일단 별관측하기 좋은날 하시고 여유되시면 다른거도 만들어주세요

**Comment by AhnJewon** [comment]
관광지 데이터를 전송할때  context에 들어가야 하는 내용은 뭔가요?
