### ISSUE TITLE
백엔드 내용 공유

### ISSUE THREAD

**Issue by yangsua** [Seobeomsu/2023_Open_Source_Project#14]
제원님, 백엔드에서 어떤내용 진행하셨는지 알려주실 수 있으신가요?
참고해야할 것 같아서 질문드립니다.
그리고 혹시 제가 진행했으면 하는 부분도 알려주시면 감사하겠습니다.

**Comment by AhnJewon** [comment]
일단 api용 웹서버와 데이터베이스 진행했고 지금은 관광 장소 크롤러 진행하고 있습니다.
