### ISSUE TITLE
front_backend 데이터 전달 api 엔드포인트

### ISSUE THREAD

**Issue by yangsua** [Seobeomsu/2023_Open_Source_Project#18]
front_backend 파일의 코드에
data 변수에 프론트엔드로 전달할 데이터가 포함되어있습니다.
HTTP GET 요청을 수신하면 /data 엔드포인트는 data 변수에 저장된 데이터를 JSON 형식으로 응답할겁니다.
프론트에서 api 엔드포인트로 get 요청을 보내서 데이터 수신가능합니다.
[https://github.com/Seobeomsu/2023_Open_Source_Project/blob/feature_star-weather/front%20_backend](url)

**Comment by Seobeomsu** [comment]
HTTP GET URL주소와
JSON 형식으로 어떻게 출력되는지 알려주세요
코드만으로는 제가 알아보기가 어렵습니다.

**Comment by yangsua** [comment]
죄송합니다. 코드가 잘못된 부분들이 있어서 수정 후 다시 커밋하도록 하겠습니다.
