### ISSUE TITLE
4월 13일 회의록

### ISSUE THREAD

**Issue by yangsua** [Seobeomsu/2023_Open_Source_Project#3]
주제: 기상정보에 따른, 야외활동하기 좋은 day 예측. 장소추천
+서브: 기상정보에 따라 다음날의 외출복 예측.

범위: 최소 청주 내에서. 1년의 기상정보 예측과 좋은 날짜 추천 필수.

백엔드 : 파이썬
프론트: 안드로이드(코틀린)

기상청 api 사용.

프론트엔드 – 백엔드 어떻게 통신할지

프론트엔드 백엔드 범위 정하기

‘last api’: 기상청 api – 백엔드 - 프론트

기능
-프론트엔드에서 데이터저장 후 
-로컬에 저장 후 서버에 송신

안드로이드 – 날짜데이터 받아와서 3개월
or 기상청 당일 데이터 받아와서

지역 – 청주
장소추천: 직접 찾아서 추천 or 카카오 api를 통해서
캘린더 형식으로, 야외활동하기 좋은 날짜 추천. 날짜를 선택해서 들어가면 청주 지도에 특정 장소 표시.
지도 api.
카카오 맵 api: https://haries.tistory.com/6
중간 프레젠테이션: api와 기능들의 계획. 앱디자인 초안. first commit.

다음 회의까지 할일:
서범수 님 – 앱화면 초안 작성, 프론트 앤드 초기 커밋
안제원 님, 양수아– 백엔드 초기 커밋백엔드 초기 커밋, 서버, 폴더 나누기, 코드 작성, api 정보 받아오는 코드 작성.

다음 회의 :로직

카톡과 이슈 열심히 활용.

앱 이름: "놀러갈래"

**Comment by yangsua** [comment]
4월 13일 회의록입니다.
그대로 옮기는 건데 이래저래 바빠서 생각을 못했습니다.
죄송합니다.
앞으로 적극적으로 임하겠습니다.

**Comment by yangsua** [comment]
회의록이니 제가 닫겠습니다.

**Comment by Seobeomsu** [comment]
고생하셨습니다
