### ISSUE TITLE
기존  유사 사이트들의 한계

### ISSUE THREAD

**Issue by yangsua** [Seobeomsu/2023_Open_Source_Project#5]
true 청주 -> 관광지에 가기 좋은 날씨에 대한 정보 없음
첫 화면 날씨 -> 직접 관광지를 입력해서 날씨 예보를 제공받을 수 있으나, 
청주에 어떠한 관광지가 있는지, 또 관광지의 위치는 어디인지 알 수 없음.

즉, 기존에 있는 사이트들은 우리가 만들고자 하는 앱과 완전히 일치하지 않는다.

**Comment by Seobeomsu** [comment]
레저에 빠지다 -> 야외스포츠 장소 추천 및 예매 , 레저상품 판매 or 중고나라처럼 회원간 교환
데이트팝 - 여행지, 맛집, 카페,  놀거리 추천 , 이를 코스로 만들어 사용자에게 안내
트리플 -> 여행계획 , 가계부 , 관광지관련 가이드제공 간단한 날씨, 환율정보 제공

**Comment by Seobeomsu** [comment]
레저에 빠지다 -> 야외스포츠 장소 추천 및 예매 , 레저상품 판매 or 중고나라처럼 회원간 교환
데이트팝 - 여행지, 맛집, 카페, 놀거리 추천 , 이를 코스로 만들어 사용자에게 안내
트리플 -> 여행계획 , 가계부 , 관광지관련 가이드제공 간단한 날씨, 환율정보 제공
true 청주 -> 관광지에 가기 좋은 날씨에 대한 정보 없음
첫 화면 날씨 -> 직접 관광지를 입력해서 날씨 예보를 제공받을 수 있으나,
청주에 어떠한 관광지가 있는지, 또 관광지의 위치는 어디인지 알 수 없음.

기본 레저앱의 대부분은 관광지 추천을 하고, 이 관광지에서 사용하는 물품이나 서비스를 제공
기존에 앱들 중 첫화면날씨가 유사하나, 이 앱 또한 여행지를 찾아주지는 않는다.
즉 날씨정보를 토대로 여행지 추천해주는건 현재 존재하지 않는다.
