### ISSUE TITLE
앱 필요성에 대해 한번 써봤습니다

### ISSUE THREAD

**Issue by AhnJewon** [Seobeomsu/2023_Open_Source_Project#6]
앱 필요성: 
여행 계획을 세울때 여행지 정보 따로 날씨정보 따로 파편화 되어있음 따라서 불편함이 야기됨 여행지 정보와 날씨정보 모두 통합된 시스템 필요

교통 발달로 당일 치기 여행 잛은 여행 증가 복잡한 여행 계획 대신 간편한 여행계획의 필요성 대두 따라서 꼭 필요한 정보만이 필요함

본 앱은 날씨 예측 기반 여행지 추천 및 정보 제공으로 그러한 니즈를 충족시킬 수 있다

**Comment by Seobeomsu** [comment]
수고하셨습니다.
