### ISSUE TITLE
날씨 예보 api문제

### ISSUE THREAD

**Issue by yangsua** [Seobeomsu/2023_Open_Source_Project#9]
기상청 api를 계속해서 찾아보니 중기예보는 최대 10일까지의 각 날의 날씨를 예보하고 장기예보는 1개월 단위나 3개월 단위로 각각의 날이 아닌 평균적인 예보를 제공하고 있습니다.
이점에 대해서 어떻게 해결할 수 있을지 의견주시기 바랍니다.
[https://www.data.go.kr/data/15059468/openapi.do](url)
우선 중기예보 api url 올리겠습니다.

**Comment by Seobeomsu** [comment]
일단 중기예보 10일까지 내용으로 만들면될것같습니다.
추가적으로 장기예보 1개월단위와 3개월 단위 각각 어떤식으로 평균적인 예보를 제공하고있는지 자세한내용 올려주시면 감사하겠습니다.

**Comment by AhnJewon** [comment]
10일 이후 내용을 머신러닝으로 학습시켜 예측하는건 어떨까요?

**Comment by yangsua** [comment]
[기상청28_중기예보 조회서비스_오픈API활용가이드.zip](https://github.com/Seobeomsu/2023_Open_Source_Project/files/11492964/28_._.API.zip)
두번째 word보면 어떤식으로 예보를 제공하는지 보이실겁니다!

**Comment by yangsua** [comment]
1개월 단위와 3개월 단위도 올리겠습니다!

**Comment by yangsua** [comment]
[https://www.weather.go.kr/weather/forecast/long-range.jsp](url)
1개월과 3개월 단위는 api가 아니어서 말씀 안드렸는데 일단 사이트 url올리겠습니다.!
머신러닝도 좋은 것 같습니다!

**Comment by yangsua** [comment]
[https://www.weather.go.kr/w/weather/forecast/mid-term.do](url) 여기가 더 정확할 것 같습니다.
